export const BLOCK_TYPES = {
    TEXT: 'text',
    HEADING_1: 'heading_1',
    HEADING_2: 'heading_2',
    HEADING_3: 'heading_3',
    TODO: 'to_do',
    BULLETED_LIST: 'bulleted_list',
    NUMBERED_LIST: 'numbered_list',
    TOGGLE: 'toggle',
    QUOTE: 'quote',
    DIVIDER: 'divider',
    CALLOUT: 'callout',
    CODE: 'code',
    IMAGE: 'image',
    FILE: 'file',
    BOOKMARK: 'bookmark',
    TABLE: 'table',
    KANBAN: 'kanban',
    SNIPPET: 'snippet',
    REMINDER: 'reminder',
};

export const BLOCK_CATEGORY = {
    TEXT: 'text',
    LIST: 'list',
    STRUCTURE: 'structure',
    DIVIDER: 'quote',
    ACCENT: 'accent',
    MEDIA: 'media',
    DATA: 'data',
    OTHER: 'other',
};

export const BLOCK_CATEGORY_LABEL = {
    [BLOCK_CATEGORY.TEXT]: '텍스트',
    [BLOCK_CATEGORY.LIST]: '리스트',
    [BLOCK_CATEGORY.STRUCTURE]: '구조',
    [BLOCK_CATEGORY.DIVIDER]: '인용/구분',
    [BLOCK_CATEGORY.ACCENT]: '강조',
    [BLOCK_CATEGORY.MEDIA]: '미디어',
    [BLOCK_CATEGORY.DATA]: '데이터',
    [BLOCK_CATEGORY.OTHER]: '기타',
};

export const BLOCK_DEFINITIONS = {
    [BLOCK_TYPES.TEXT]: {
        label: 'Text',
        description: '기본 문단을 입력합니다',
        icon: '¶',
        placeholder: '텍스트를 입력하세요',
        category: BLOCK_CATEGORY.TEXT,
        create: () => ({ html: '', props: {} }),
    },
    [BLOCK_TYPES.HEADING_1]: {
        label: 'Heading 1',
        description: '큰 제목',
        icon: 'H1',
        placeholder: '제목 1',
        category: BLOCK_CATEGORY.TEXT,
        create: () => ({ html: '', props: {} }),
    },
    [BLOCK_TYPES.HEADING_2]: {
        label: 'Heading 2',
        description: '중간 제목',
        icon: 'H2',
        placeholder: '제목 2',
        category: BLOCK_CATEGORY.TEXT,
        create: () => ({ html: '', props: {} }),
    },
    [BLOCK_TYPES.HEADING_3]: {
        label: 'Heading 3',
        description: '작은 제목',
        icon: 'H3',
        placeholder: '제목 3',
        category: BLOCK_CATEGORY.TEXT,
        create: () => ({ html: '', props: {} }),
    },
    [BLOCK_TYPES.TODO]: {
        label: 'To-do',
        description: '체크 가능한 할 일',
        icon: '☑︎',
        placeholder: '할 일을 입력하세요',
        category: BLOCK_CATEGORY.LIST,
        create: () => ({ html: '', props: { checked: false } }),
    },
    [BLOCK_TYPES.BULLETED_LIST]: {
        label: 'Bulleted List',
        description: '점 리스트',
        icon: '•',
        placeholder: '항목을 입력하세요',
        category: BLOCK_CATEGORY.LIST,
        create: () => ({ html: '', props: { level: 0 } }),
    },
    [BLOCK_TYPES.NUMBERED_LIST]: {
        label: 'Numbered List',
        description: '번호 리스트',
        icon: '1.',
        placeholder: '항목을 입력하세요',
        category: BLOCK_CATEGORY.LIST,
        create: () => ({ html: '', props: { level: 0, index: 1 } }),
    },
    [BLOCK_TYPES.TOGGLE]: {
        label: 'Toggle',
        description: '접었다 펼칠 수 있는 블록',
        icon: '▸',
        placeholder: '토글 제목을 입력하세요',
        category: BLOCK_CATEGORY.STRUCTURE,
        create: () => ({ html: '', props: { expanded: true }, children: [] }),
    },
    [BLOCK_TYPES.QUOTE]: {
        label: 'Quote',
        description: '인용문',
        icon: '❝',
        placeholder: '인용문을 입력하세요',
        category: BLOCK_CATEGORY.DIVIDER,
        create: () => ({ html: '', props: {} }),
    },
    [BLOCK_TYPES.DIVIDER]: {
        label: 'Divider',
        description: '구분선',
        icon: '―',
        placeholder: '',
        category: BLOCK_CATEGORY.DIVIDER,
        create: () => ({ html: '', props: {} }),
        isVoid: true,
    },
    [BLOCK_TYPES.CALLOUT]: {
        label: 'Callout',
        description: '아이콘과 배경으로 강조',
        icon: '❗',
        placeholder: '콜아웃 내용을 입력하세요',
        category: BLOCK_CATEGORY.ACCENT,
        create: () => ({ html: '', props: { icon: '💡', tint: 'blue' }, children: [] }),
    },
    [BLOCK_TYPES.CODE]: {
        label: 'Code',
        description: '코드/명령문 기록',
        icon: '</>',
        placeholder: '코드를 입력하세요',
        category: BLOCK_CATEGORY.ACCENT,
        create: () => ({ html: '', props: { language: 'text' } }),
    },
    [BLOCK_TYPES.IMAGE]: {
        label: 'Image',
        description: '이미지를 삽입합니다',
        icon: '🖼️',
        placeholder: '이미지 캡션을 입력하세요',
        category: BLOCK_CATEGORY.MEDIA,
        create: () => ({ html: '', props: { url: '', caption: '' } }),
    },
    [BLOCK_TYPES.FILE]: {
        label: 'File',
        description: '파일을 첨부합니다',
        icon: '📎',
        placeholder: '파일 설명을 입력하세요',
        category: BLOCK_CATEGORY.MEDIA,
        create: () => ({ html: '', props: { name: '', size: '', url: '' } }),
    },
    [BLOCK_TYPES.BOOKMARK]: {
        label: 'Bookmark',
        description: '링크 미리보기 카드',
        icon: '🔖',
        placeholder: '설명을 입력하세요',
        category: BLOCK_CATEGORY.MEDIA,
        create: () => ({ html: '', props: { url: '', title: '', description: '', status: 'idle' } }),
    },
    [BLOCK_TYPES.TABLE]: {
        label: 'Table',
        description: '간단한 표를 만듭니다',
        icon: '⌗',
        placeholder: '',
        category: BLOCK_CATEGORY.DATA,
        create: () => ({
            html: '',
            props: {
                rows: 3,
                columns: 3,
                data: Array.from({ length: 3 }, () => Array.from({ length: 3 }, () => ({ value: '' }))),
            },
        }),
    },
    [BLOCK_TYPES.KANBAN]: {
        label: 'Kanban',
        description: '개인용 분류 보드',
        icon: '▤',
        placeholder: '',
        category: BLOCK_CATEGORY.DATA,
        create: () => ({
            html: '',
            props: {
                columns: [
                    { id: 'todo', title: '할 일', cards: [] },
                    { id: 'doing', title: '진행 중', cards: [] },
                    { id: 'done', title: '완료', cards: [] },
                ],
            },
        }),
    },
    [BLOCK_TYPES.SNIPPET]: {
        label: 'Snippet',
        description: '저장한 문구/구성을 삽입',
        icon: '✶',
        placeholder: '스니펫 내용을 입력하세요',
        category: BLOCK_CATEGORY.OTHER,
        create: () => ({ html: '', props: { snippetId: null } }),
    },
    [BLOCK_TYPES.REMINDER]: {
        label: 'Reminder',
        description: '날짜/시간 칩 추가(개인 알림)',
        icon: '⏰',
        placeholder: '',
        category: BLOCK_CATEGORY.OTHER,
        create: () => ({
            html: '',
            props: {
                date: null,
                time: null,
                completed: false,
            },
        }),
        isInline: true,
    },
};

export const INLINE_FORMATS = {
    bold: { command: 'bold', label: 'B', shortcut: '⌘+B' },
    italic: { command: 'italic', label: 'I', shortcut: '⌘+I' },
    strike: { command: 'strikeThrough', label: 'S', shortcut: '⌘+Shift+S' },
    code: { command: 'formatBlock', value: 'pre', label: '{ }', shortcut: '⌘+E' },
    link: { command: 'createLink', label: 'Link', shortcut: '⌘+K' },
};

export const SLASH_PALETTE_CATEGORIES = [
    { id: 'recent', label: '최근 사용' },
    { id: BLOCK_CATEGORY.TEXT, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.TEXT] },
    { id: BLOCK_CATEGORY.LIST, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.LIST] },
    { id: BLOCK_CATEGORY.STRUCTURE, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.STRUCTURE] },
    { id: BLOCK_CATEGORY.DIVIDER, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.DIVIDER] },
    { id: BLOCK_CATEGORY.ACCENT, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.ACCENT] },
    { id: BLOCK_CATEGORY.MEDIA, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.MEDIA] },
    { id: BLOCK_CATEGORY.DATA, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.DATA] },
    { id: BLOCK_CATEGORY.OTHER, label: BLOCK_CATEGORY_LABEL[BLOCK_CATEGORY.OTHER] },
];

export const REMINDER_PRESETS = [
    { id: 'later-today', label: '오늘 늦게', offsetHours: 4 },
    { id: 'tomorrow', label: '내일', offsetDays: 1 },
    { id: 'next-week', label: '다음 주', offsetDays: 7 },
];

export const RECENT_SLASH_LIMIT = 3;
